steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/train',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/train'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build API container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/api',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push API container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/api'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build data container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/data',
    '-f',
    'dockerfiles/data.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push data container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/data'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build frontend container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/frontend',
    '-f',
    'dockerfiles/frontend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push frontend container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/frontend'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
