steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build API container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/api',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push API container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/api'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'api',
    '--image',
    'europe-west1-docker.pkg.dev/clean-sylph-484508-h9/ml-ops-artifact-registry/api',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--allow-unauthenticated',
    '--service-account',
    'github-actions@clean-sylph-484508-h9.iam.gserviceaccount.com',
    '--set-env-vars',
    'GCS_LOGGING_BUCKET=ml_ops_data_bucket_46,GCS_MODEL_BUCKET=ml_ops_data_bucket_46,GCS_MODEL_PATH=experiments/run1/model/model.pth,GCS_VOCAB_PATH=experiments/run1/model/vocab.pt'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
