name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11", "3.12"]
        torch-version: ["2.5.1", "2.4.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --locked --dev
          uv pip install torch==${{ matrix.torch-version }} torchvision --index-url https://download.pytorch.org/whl/cpu
          uv tree

      - name: Run tests & coverage
        env:
          UV_HTTP_TIMEOUT: 1200
        run: |
          uv run coverage run -m pytest tests/
          uv run coverage report -m

      # - name: Start API server
      #   run: |
      #     uv run uvicorn ml_ops_project.api:app --host 127.0.0.1 --port 8000 &
      #     sleep 3  # Wait for server to start

      # - name: Run load tests
      #   run: |
      #     uv run python -m http.server 8000 &
      #     sleep 2
      #     uv run locust -f tests/load_tests/locustfile.py --host http://localhost:8000 --users 50 --spawn-rate 5 --run-time 30s --headless
