name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11", "3.12"]
        torch-version: ["2.5.1", "2.4.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --locked --dev
          uv pip install torch==${{ matrix.torch-version }} torchvision --index-url https://download.pytorch.org/whl/cpu
          uv tree

      - name: Run unit tests & coverage
        env:
          UV_HTTP_TIMEOUT: 1200
        run: |
          uv run coverage run -m pytest tests/unittests/
          uv run coverage report -m

  build:
    needs: test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Submit build
      run: gcloud builds submit . --config configs/cloudbuild_api.yaml

    - name: Submit build
      run: gcloud builds submit . --config configs/cloudbuild_frontend.yaml

    - name: Submit build
      run: gcloud builds submit . --config configs/cloudbuild_train.yaml
